import { Loader } from "@react-three/drei";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Grain from "../components/Grain";
import Header from "../components/Header";
import Parallax from "../components/Parallax";
import SmoothScroll from "../components/SmoothScroll";
import Menu from "../components/three/Menu";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>The Ringr.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu></Menu>
      <SmoothScroll>
        <section className="land">
          <div className="land__title">
            <p>OPTO</p>
            <h1>Ringr.</h1>
          </div>
        </section>
        <section></section>
        <section></section>
      </SmoothScroll>
    </div>
  );
};

export default Home;
